name: Repository synchronization

on:
  workflow_run:
    workflows:
      - Bump version
    types:
      - completed
  workflow_dispatch:

jobs:
  prepare:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/'))
    runs-on: ubuntu-latest
    outputs:
      replacements: ${{ steps.getReplacementsStep.outputs.replacements }}
    steps:
      - uses: rees46/workflow/.github/actions/sync/read-replacements@master
        id: getReplacementsStep
        with:
          appId: ${{ vars.PUBLIVERSIONER_ID }}
          appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
          replacementsPath: github/repo-sync-replacements/ios-sdk.yml

  repoSync:
    needs: prepare
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: rees46/workflow/.github/workflows/reusable-repo-sync.yml@master
    secrets:
      appSecret: ${{ secrets.PERSONACLICK_COURIER_SECRET }}
    with:
      appId: ${{ vars.PERSONACLICK_COURIER_ID }}
      replacements: ${{ needs.prepare.outputs.replacements }}
      targetRepository: personaclick/ios-sdk
      repositoryOwner: personaclick
      reviewerUsername: ${{ vars.REVIEWER_USERNAME }}
